[tool.pytest.ini_options]
log_cli = true
log_cli_level = 'NOTSET'
log_cli_format = '%(asctime)-15s  |%(levelname)+8s| %(name)+30s |  %(message)s'
log_cli_date_format='%Y-%m-%d %H:%M:%S'
addopts = '-vv --cov=. --cov-report html'
